add styles to texts
gusm217/Words_Counter pull request #4
Opened 2020-10-31 23:35 UTC by gusm217

Add styles to texts.

2020-10-31 23:37 UTC, Mateus-Resende requested changes

2020-10-31 23:37 UTC, Mateus-Resende commented on src/TextField-container.css
> +.text-counter {
faltou remover a classe que não está sendo utilizada mais

2020-11-02 19:49 UTC, gusm217 reviewed
Reviewd! Thx

2020-11-02 20:13 UTC, gusm217 reviewed
Reviewd! Thx

2020-11-02 20:13 UTC, merged